spring:
  datasource:
    url: jdbc:mariadb://workbooks.cxj3hj7vxykm.ap-northeast-2.rds.amazonaws.com:3306/workbooks
    driver-class-name: org.mariadb.jdbc.Driver
    username: dali
    password: workbooks0831

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  auth:
    token-secret: navysworkbooksjwtkeysecretnavysworkbooksjwtkeysecretnavysworkbooksjwtkeysecret
    token-expiration-time: 1209600000
  oauth:
    google:
      provider: google
      client-id: 674664597564-8eomtt8p4rjjqnm26ep6m3srjfchonel.apps.googleusercontent.com
      client-secret: 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
      authorization-grant-type: authorization_code
#      redirect-uri : http://localhost:3000/auth/google/callback
      redirect-uri : https://workbooks.ga/auth/google/callback
      token-uri: https://oauth2.googleapis.com/token
#      authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=674664597564-8eomtt8p4rjjqnm26ep6m3srjfchonel.apps.googleusercontent.com&scope=openid%20email&redirect_uri=http://localhost:3000/auth/google/callback
      authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=674664597564-8eomtt8p4rjjqnm26ep6m3srjfchonel.apps.googleusercontent.com&scope=openid%20email&redirect_uri=https://workbooks.ga/auth/google/callback
    kakao:
      provider: kakao
      client-id: d3a0fd443a4f80222b5565e5eea4966e
      client-secret: CDIQFeo6PXAYYSPnY37tA90LLN7aDKzh
      authorization-grant-type: authorization_code
#      redirect-uri : http://localhost:3000/auth/kakao/callback
      redirect-uri : https://workbooks.ga/auth/kakao/callback
      token-uri: https://kauth.kakao.com/oauth/token
#      authorization-uri: https://kauth.kakao.com/oauth/authorize?client_id=d3a0fd443a4f80222b5565e5eea4966e&redirect_uri=http://localhost:3000/auth/kakao/callback&response_type=code
    authorization-uri: https://kauth.kakao.com/oauth/authorize?client_id=d3a0fd443a4f80222b5565e5eea4966e&redirect_uri=https://workbooks.ga/auth/kakao/callback&response_type=code
    naver:
      provider: naver
      client-id: TXkw2k0nH1HXcMK432a2
      client-secret: d3TsNoOKUQ
      authorization-grant-type: authorization_code
      redirect-uri : http://localhost:3000/naver/kakao/callback
      token-uri: https://nid.naver.com/oauth2.0/token
      authorization-uri: https://nid.naver.com/oauth2.0/authorize